title: White leaf
description: White leaf is something we can write whatever we want

url: http://anirudh708.github.com/white-leaf
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
paginate: 5

plugins:
  - jekyll-paginate

navigation:
 - title: Home
   url: /index.html
 - title: Tags
   url: /tags
 - title: About
   url: /about
 - title: Contact
   url: /contact


social:
   github: anirudh708
   twitter: w_anirudh
   facebook: rockstreetani
   email: w.anirudh92@gmail.com

